apiVersion: v1
kind: Pod
metadata:
  name: web-server
  namespace: rbac-demo
  labels:
    role: web
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: rbac-demo
spec:
  selector:
    role: web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
